esphome:
  name: sonoff-r2
  friendly_name: Sonoff R2
  name_add_mac_suffix: true

  project:
    name: ESPHome_Unleashed.Sonoff R2
    version: "1.0"

esp8266:
  board: esp8285

logger:

api:

ota:
  
dashboard_import:
  package_import_url: github://Martian-Dylan3/ESPHome_Unleashed/Sonoff_R2_ESPHome.yaml@main
  import_full_config: true

wifi:

  ap:
    password: "esphome1234"

captive_portal:
    
binary_sensor: # Button
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    on_press:
      - switch.toggle: relay

switch: # Relay
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay

status_led: # Blue status indicator
  pin:
    number: GPIO13
    inverted: false

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
